services:
  db:
    image: postgres
    container_name: db
    ports:
      - 2345:5432

  app:
    build: .
    container_name: app_test
    ports:
      - 5000:4000
    env_file:
      - .env.test
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    command:
      - sh
      - -c
      - |
        npm run test:migration:apply
        npm run test:watch
